postgres:
  password:
    _default: deFaulTPasswOrdForChECk
    dev: ##
    stage: ##
    production: ##

dex:
  clientID:
    _default: ##
  clientSecret:
    _default: ##

gogomonia:
  password:
    _default: deFaulTPasswOrdForChECk
    dev: ##
    stage: ##
    production: ##